content_type_required:
  name: contentType
  in: header
  required: true
  schema:
    type: string
  example: application/json

auth_token_required:
  name: Authorization
  in: header
  required: true
  schema:
    type: string
  example: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvYmplY3RfaWQiOiJhZjJjM2YzYy1JlYXRlZCI6MTU5NzkwODc1NH0.6CV0oXTei4WqrEF3UAO6yJPze78Ihy16a2w_bovLNF

auth_garant_type_required:
  name: AUTH-GARANT-TYPE
  in: header
  required: true
  schema:
    type: string
    enum:
      - refresh_token
  example: refresh_token

password_change_token_required:
  name: token
  in: query
  description: Одноразовый токен для смены пароля
  required: true
  schema:
    type: string
    example: "8ac44e0b538acf29e40ad27eee8909ba9b0e2b3c3a6cd271e030f4245aeba7be"

page:
  name: page
  in: query
  description: Номер страницы
  required: false
  schema:
    type: integer
    default: 1
    example: 1

page_size:
  name: page_size
  in: query
  description: Кол-во элементов на одной странице
  required: false
  schema:
    type: integer
    default: 20
    example: 20

keyword_filter:
  name: keyword
  in: query
  description: |
    Фильтр по ключевому слову
  required: false
  schema:
    type: string

year:
  name: year
  in: query
  description: |
    Год
  schema:
    type: integer
    nullable: false
    default: "<current year, example: 2022>"
    example: 2022

month:
  name: month
  in: query
  description: |
    Месяц, 1-12
  schema:
    type: integer
    nullable: false
    default: "<current month, example: 1>"
    example: 1

media_id_required:
  name: media_id
  in: query
  description: uuid4 идентификатор медиа-файла
  required: true
  schema:
    type: string
    format: uuid
    example: "f4dbc625-5101-4a17-8b26-237ecea92b43"

folder_id_required:
  name: folder_id
  in: query
  description: uuid4 идентификатор каталога
  required: true
  schema:
    type: string
    format: uuid
    example: b2e8cb1f-0662-4ddd-abd7-bb5245b01526

folder_id:
  name: folder_id
  in: query
  description: uuid4 идентификатор каталога
  schema:
    type: string
    format: uuid
    example: b2e8cb1f-0662-4ddd-abd7-bb5245b01526

folder_parent_id_required:
  name: parent_id
  in: query
  description: uuid4 идентификатор каталога
  required: true
  schema:
    type: string
    format: uuid
    example: b2e8cb1f-0662-4ddd-abd7-bb5245b01526

folder_parent_id:
  name: parent_id
  in: query
  description: uuid4 идентификатор каталога
  nullable: true
  schema:
    type: string
    format: uuid
    example: b2e8cb1f-0662-4ddd-abd7-bb5245b01526

folder_title:
  name: title
  in: query
  description: Фильтр параметр по названию каталога
  schema:
    type: string
    example: Работа

note_title:
  name: title
  in: query
  description: Фильтр параметр по названию заметки
  schema:
    type: string
    example: Работа

note_by_folder:
  name: by_folder
  in: query
  description: Фильтровать по каталогу
  schema:
    type: boolean

note_id_required:
  name: note_id
  in: query
  description: uuid4 идентификатор заметки
  required: true
  schema:
    type: string
    format: uuid
    example: df19043e-39b1-4b28-a39c-ea29038e1e83

parent_note_id_required:
  name: parent_note_id
  in: query
  description: uuid4 идентификатор заметки
  required: true
  schema:
    type: string
    format: uuid
    example: df19043e-39b1-4b28-a39c-ea29038e1e83

child_note_id_required:
  name: child_note_id
  in: query
  description: uuid4 идентификатор заметки
  required: true
  schema:
    type: string
    format: uuid
    example: df19043e-39b1-4b28-a39c-ea29038e1e83
