content_type_required:
  name: contentType
  in: header
  required: true
  schema:
    type: string
  example: application/json

auth_token_required:
  name: Authorization
  in: header
  required: true
  schema:
    type: string
  example: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvYmplY3RfaWQiOiJhZjJjM2YzYy1JlYXRlZCI6MTU5NzkwODc1NH0.6CV0oXTei4WqrEF3UAO6yJPze78Ihy16a2w_bovLNF

auth_garant_type_required:
  name: AUTH-GARANT-TYPE
  in: header
  required: true
  schema:
    type: string
    enum:
      - refresh_token
  example: refresh_token

password_change_token_required:
  name: token
  in: query
  description: Одноразовый токен для смены пароля
  required: true
  schema:
    type: string
    example: "8ac44e0b538acf29e40ad27eee8909ba9b0e2b3c3a6cd271e030f4245aeba7be"

page:
  name: page
  in: query
  description: Номер страницы
  required: false
  schema:
    type: integer
    default: 1
    example: 1

page_size:
  name: page_size
  in: query
  description: Кол-во элементов на одной странице
  required: false
  schema:
    type: integer
    default: 20
    example: 20

keyword_filter:
  name: keyword
  in: query
  description: |
    Фильтр по ключевому слову
  required: false
  schema:
    type: string

year:
  name: year
  in: query
  description: |
    Год
  schema:
    type: integer
    nullable: false
    default: "<current year, example: 2022>"
    example: 2022

month:
  name: month
  in: query
  description: |
    Месяц, 1-12
  schema:
    type: integer
    nullable: false
    default: "<current month, example: 1>"
    example: 1

media_id_required:
  name: media_id
  in: query
  description: uuid4 идентификатор медиа-файла
  required: true
  schema:
    type: string
    format: uuid
    example: "f4dbc625-5101-4a17-8b26-237ecea92b43"
