openapi: '3.0.0'
servers:
- url: http://127.0.0.1:8000/
  description: локальный сервер
info:
  $ref: './info.yaml'
paths:
  $ref: './paths.yaml'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Базовая информация
  - name: Регистрация и авторизация
  - name: Пользователи
  - name: Каталоги
  - name: Заметки
